codecov:
  require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  range: "60...100"
  status:
    project:
      default:
        target: auto
        threshold: 0.5%

ignore:
  - "crates/xtask"  # Part of the build system
  - "src"           # CLI (not tested yet)
  - "crates/weaver_forge/codegen_examples/expected_codegen" # Generated code